Gateway.ReportError: get proper caller name
- GetCallerName() assumes caller is two frames above
- therefore, delegate to LogError only after GetCallerName()